services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-13T20-26-02Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: ROOTUSER123
    volumes:
      - ./volumes/minio/data:/data
    ports:
      - "${MINIO_CONSOLE}:9000"
      - "${MINIO_HTTP}:9090"
    command: server /data --console-address ":9090"
